---
title: "Introduction"
author: "Lara Wootton"
date: "11/05/2020"
output: 
  pdf_document:
      latex_engine: xelatex
bibliography: General_intro_refs.bib
csl: harvard-university-of-cape-town.csl
---





# Abstract

The Greater Cape Floristic Region (GCFR) of South Africa has one of the most biodiverse floras in the world. Although ecological speciation is thought to be a primary mechanism behind diversification in the GCFR, it has recently been hypothesised that non-ecological speciation may have an influential role in driving diversification in the montane "sky islands" of the GCFR, as the peaks of the Cape Fold Mountains form 'sky islands' separated by deep valleys, potentially disrupting gene flow between high-elevation populations and enabling the formation of cryptic species. This work seeks to test the relative importance of ecological versus non-ecological processes in powering speciation at different elevations in the GCFR, and to assess the existence of multiple, range-restricted cryptic species at high elevations. The Cape grass genus *Ehrharta* is an ideal system in which to do this, as it contains low-, mid-, and high-elevation lineages, with a previously documented adaptive radiation in the Succulent Karoo. Population-level phylogenetic analyses based on targeted enrichment sequencing data show that _E. rupestris_ and _E. setacea_, as currently defined, are polyphyletic, and reveal multiple distinct monophyletic lineages within the Ramosa, Rehmannii and Setacea clades. Analysis of genotyping-by-sequencing and morphological data, together with evidence of sympatry, confirm these lineages to be distinct entities, resulting in 13-16 putative new species, of which several can be considered cryptic. Following a molecular dating analysis based on 12 replicate sets of 50 loci, the crown age of _Ehrharta_ was found to originate 28 Ma, a date substantially older than previous estimates. The high-elevation Setacea clade had high rates of morphological and genetic change relative to the rest of the Cape _Ehrharta_, as well as showing subtle ecological differentiation.

Here, I present a population-level phylogeny of the Cape _Ehrharta_, focusing on the mid- and high-elevation clades. An integrative taxonomic approach is used to evaluate whether these lineages of _Ehrharta_ contain potential cryptic species, on the basis of genome-wide SNP and targeted-enrichment sequencing, morphological and ecological datasets. The relative importance of ecological and non-ecological processes at different elevations is then assessed by using a time calibrated species tree to compare rates of morphological change, and rates of synonymous versus non-synonymous substitution. I find that _E. setacea_ and _E. rupestris_ are highly polyphyletic, and that there is evidence for 13-16 new taxa in the mid- and high-elevation clades, of which several are cryptic. The high-elevation Setacea clade had high rates of morphological and genetic change relative to the rest of the Cape _Ehrharta_, as well as showing subtle ecological differentiation. This demonstrated that the relative importance of non-ecological processes in driving speciation does not increase in higher-elevation clades. Rather, it is suggested that diversification in the Cape _Ehrharta_ was triggered by a combination of intrinsic and extrinsic factors unique to each clade, tying in with a growing body of research arguing that it is no longer sufficient to generalise a radiation as 'adaptive' or 'non-adaptive'. Instead, mountain radiations require an integrated approach to untangle the subtle interaction of geographic and ecological triggers.  

Contrary to predictions, the high-elevation clade of _Ehrharta_ showed greater rates of morphological and molecular change than the low-elevation clade, implying that non-ecological speciation may not be the main instigator of diversification in the montane regions of the GCFR.

 I suggest that alternating wet and dry periods due to the climate cycles of the Pleistocene, may have caused bursts of adaptive speciation within _Ehrharta_. 



# General introduction

Accurate species delimitation is important, since it underpins a diverse range of other fields, from conservation biology and ecology to medicine. For example, the categorisation and protection of endangered species is often based on species' ranges and abundance. Thus, incorrect species delimitation may result in poor conservation decisions, and may even determine whether management interventions prevent population decline and extinction [@Chenuil2019]. Human health and safety also depends on accurate species delimitation, with poor species delimitation reducing our ability to prevent disease and develop new medicines. For instance, recent genetic studies have found that several malaria-carrying mosquito species actually comprise of complexes of species with behavioural differences which warrant unique health interventions [@Stevenson2012; @Lobo2015]. Similarly, the taxonomic instability of venomous snake genera hinders our ability both to create anti-venoms and to explore the potential therapeutic properties of snake venom [@Carrasco2016; @Wuester1996]. Species concepts also underpin our evolutionary hypotheses, our understanding of ecological interactions, and our study of ecosystem function. Until recently, it has been thought that 8.7 million eukaryote species exist on the planet [@Mora2011], but the application of genetic techniques for species delimitation suggests that the true number may actually be much greater, predominantly owing to the discovery of cryptic species [@Scheffers2012; @Adams2014; @Struck2018].

Cryptic species are species which are morphologically similar, but genetically distinct [@Struck2018]. Often, cryptic species are initially classified as a single taxon, only to be found later to consist of two or more unique species [@Pfenninger2007; @Bickford2007]. Despite similarities in their appearance, cryptic species have been shown to play different functional and ecological roles [@Meester2016], preferring different microhabitats [@Guden2018], and having contrasting environmental tolerances [@Meester2011]. Taxonomists have traditionally described species on the basis of morphology, differences in morphology being taken as evidence of reproductive isolation, an important criterion for species delimitation under the Biological Species Concept [@Mayr1942]. However, the genetic distinctness of morphologically similar taxa implies that mate recognition attibutes, such as calls, smells, and colour spectra which we are unable to see, may be equally important in reproductive isolation. In recent years, cryptic species have been discovered in abundance across all taxa and biomes [@Pfenninger2007; @Beheregaray2007; @Janzen2017]. For example, nearly 60% of recently described mammalian species are from cryptic complexes [@Ceballos2009], even in charismatic taxa such as giraffes and elephants [@Brown2007; @Roca2001]. However, there is a bias in cryptic species research, with many studies being conducted on marine meiofauna, but few in plants and even less in fungi and insects, among others [@Bickford2007]. 

The origin of cryptic species is evolutionarily intriguing, but understudied. Nonetheless, several different mechanisms that could cause cryptic speciation have been postulated to date. A commonly cited explanation for cryptic species is that such species are young [@Knowlton1993; @Reidenbach2012]. If two sister species have recently diverged, insufficient time may have passed for them to have accumulated noticeable phenotypic differences [@Struck2019]. Alternatively, cryptic species may be generated under convergent or parallel evolution [@Tang2019], where unrelated species evolve a similar morphology due to shared environmental pressures. For example, @Swift2016 found that jellyfish species from distantly related ancestors converged on the same morphology after moving from a marine environment to a lake environment. Finally, species may undergo stasis, where their morphology remains unchanged for millions of years despite substantial genetic divergence [@Wada2013; @Struck2019]. Stasis due to stabilising selection can occur when strong environmental drivers cause a single phenotype to be strongly advantageous. Morphological stasis may also be a consequence of niche conservatism [@Wiens2004]. Species exhibiting niche conservatism track suitable habitat, rather than adapting to environmental heterogeneity and change. Such change may thus result in habitat fragmentation, population isolation, and, ultimately, vicariant speciation [@Kozak2006]. This process is known as non-ecological speciation, because species split not in response to divergent selection, but as a consequence of neutral processes such as genetic drift [@Rundell2009].

The Greater Cape Floristic Region (GCFR) is a hotspot of biological diversity, containing over approximately 11,500 plant species, in an area of under 200,000 km$^2$ [@Goldblatt2002; @Myers2000; @Snijman2013]. The richness of the Cape flora can be attributed to three main factors. The first is the environmental heterogeneity of the GCFR, which describes variability in both soil characteristics [@Cramer2019] and rainfall regime, as well as a rugged topography, with the Cape Fold mountains extending into the north and east of the GCFR, and rising to a maximum elevation of 2249 m above sea level [@Manning2012]. This heterogeneity may facilitate speciation both by providing gradients along which ecological speciation can occur [@Linder1985], and by providing a mosaic of habitats within which differentiation by non-ecological divergence can take place [@Verboom2015]. Secondly, a comparatively stable Pleistocene climate is thought to have promoted diversity by reducing extinction [@Dynesius2000], this effect being particularly pronounced in the southwestern GCFR, which shows both the highest overall plant species richness and an over-representation of narrow-range endemics [@Cowling2002; @Cowling2017; @Wuest2019; @Linder2019; @Colville2020]. A third factor potentially influencing the richness of the Cape flora is the onset of increasingly arid and seasonal climate during the late Miocene, this being attributed to a combination of factors, including the development of the Benguela Upwelling system, changes in Antarctic glaciation and the tectonic uplift along the eastern rim of southern Africa [@Siesser1980; @Zachos2001; @Dupont2011; @Rommerskirchen2011]. By completely transforming the lowland habitats of the Cape [@Hoffmann2015], such change may have created opportunities for adaptive radiation [@Richardson2001; @Verboom2003]. However, it may also have prompted isolation of montane habitats, thereby providing a stimulus for non-ecological speciation [@Forest2007; @Britton2014]. 

The high-elevation region of the GCFR lends itself to non-ecological speciation as it is archipelagic in nature, the mountain peaks functioning as climatically- and geologically-isolated islands surrounded by a 'sea' of lowland habitat. Many of the GCFR species that occur at high-elevations have small ranges, and sister species often display strong range exclusivity [@Verboom2015], which is characteristic of species generated through non-ecological speciation [@Kozak2006; @Boucher2016; @CzekanskiMoir2019]. High-elevation clades in the GCFR have also been shown to diversify within their elevational bands [@Verboom2015], and not solely as a result of the Late-Miocene aridification. Consequently, it has been suggested that the relative importance of ecological and non-ecological speciation processes may vary with elevation in the GCFR, with primarily ecological speciation occurring at low- to mid-elevations, and with non-ecological speciation dominating at high-elevations [@Verboom2015]. If this is correct, then low-elevation clades that diversified via adaptive radiations should show higher rates of phenotypic and molecular evolution than high-elevation clades. In addition, high-elevation lineages should exhibit similar morphologies, small ranges, and phylogenetic niche conservatism [@Kozak2006; @CzekanskiMoir2019]. There are already case studies illustrating the potential prevalence of non-ecological speciation in the montane regions. For example, @Britton2014 found that the high-elevation Cape sedge, _Tetraria triangularis_, consisted of multiple, ecologically similar cryptic species. Similarly, topographically isolated white _Protea_ populations exhibit limited geneflow between populations, potentially qualifying as distinct evolutionary species [@Prunier2010]. If non-ecological speciation is indeed the dominant mode of speciation at high-elevations, it is possible that the GCFR is even more diverse than previously thought, with a host of cryptic species potentially waiting to be discovered within the montane regions.

The Cape grass genus _Ehrharta_ Thunb. represents an ideal model system within which to test whether speciation process varies with elevation in the GCFR. The genus currently consists of approximately 45 taxa (species and subspecies) and has a Gondwanan distribution, with species occurring in Australasia, New Zealand, Malesia, Reunion, Madagascar and Africa. The majority of species (@number), however, form a GCFR-endemic clade which comprises a core low-elevation clade that is subtended by a grade of mid- to high-elevation lineages [@GibbsRussell1987; @Verboom2003]. This low-elevation clade, which associates primarily with summer-arid renosterveld and succulent karoo scrub habitats, has been shown to have undergone an adaptive radiation in response to the Late Miocene aridification, and has been interpreted as the primary radiation in _Ehrharta_ [@Verboom2003; @Verboom2004]. However, although the mid- and high- elevation lineages of Cape _Ehrharta_ comprise just six species in total, four of these species (Fig. 1) contain multiple subspecies. In addition, field observations suggest that there may be more subtle morphological differentiation in the high-elevation clades than current taxonomy suggests, hinting at the existence of cryptic species. 

Therefore, this work takes advantage of the opportunity _Ehrharta_ offers to both assess the existence of multiple, range restricted cryptic species at high elevations, and to test explicitly the relative potential importance of neutral versus adaptive processes in powering speciation at low and high elevations in the GCFR. In Chapter 2, I present a population-level phylogenic analysis of the Cape _Ehrharta_, focusing on the mid- and high-elevation clades (Fig. 1). I then employ an integrative taxonomic approach (@Dayrat2005) to evaluate whether the mid- and high-elevation lineages of _Ehrharta_ contain potential cryptic species, on the basis of genome-wide SNP and targeted-enrichment sequencing, morphological and ecological datasets. Chapter 3 presents a time-calibrated tree of the Cape _Ehrharta_, which is used to test whether rates of morphological and molecular evolution differ between clades, therefore expanding our understanding of the role that ecological versus non-ecological speciation plays in generating the biodiversity of GCFR. 



