---
title: "Introduction"
author: "Lara Wootton"
date: "11/05/2020"
output: 
  pdf_document:
      latex_engine: xelatex
bibliography: Chapt2_refs.bib
csl: harvard-university-of-cape-town.csl
---

# Chapt 2 intro

The definition of a species has been a controversial topic in biodiversity science, largely because there is no single criterion that satisfactorily defines a species across all living organisms [@Mayden1997, @Queiroz2005, more refs]. De Queiroz (2007) realised that the dissonance between species definitions was due to the speciation process itself. As a lineage diverges into two, it accumulates differences in morphology, genetic composition, ecology and degree of reproductive isolation. However, depending on the taxon, the order in which these features appear can vary, with some features occasionally not arising at all. This creates a grey zone in the speciation process, in which it can be ambiguous whether or not incipient species have effectively differentiated (@Queiroz1998). While most contemporary species concepts accept that a species is an independently evolving lineage [@Queiroz2007], determining when speciation has occurred during the gradual divergence of two lineages can often be difficult. 

It has become clear that the heterogeneity in the speciation process meant that using single criteria to delimit species was insufficient [@Wiley1978, @Frost1995, @Queiroz2005, @Padial2008]. Therefore, a new, holistic paradigm of taxonomy, called integrative taxonomy [@Dayrat2005, @Padial2010], was proposed to inform more robust species delimitation. Integrative taxonomy emphasises that multiple lines of genetic, morphological, phylogenetic and ecological evidence should be examined before delimiting and describing a species [@Dayrat2005, @Padial2010]. Despite the extensive implementation of integrative taxonomy (Dayrat's 2005 paper has been cited nearly 1400 times to date), and the application of similar integrative approaches by numerous others, morphology remains one of the most important criteria for species delimitation, especially for plant taxa [@Rouhan2014, @Treurnicht2017]. This is often due to concerns that over-reliance on genetic data will lead to taxonomic inflation [@Isaacs2004, @Coates2018, @Tattersall2007], even though the use of genetic information has also led to the reduction of the number of species in some groups [@Burbrink2000, @Devey2008]. Cryptic plant species therefore present a challenge to delimit due to the absence of defining morphological features. Although molecular barcoding was initially touted as a solution to circumscribe obscure species, and was proven to be efficient in many cases, especially in animals [@Hebert2004], it can suffer from several issues, including taxonomic decisions made on arbitrary genetic differences, the inappropriate resolution of barcoding genes for certain taxa, and difficulties of linking new DNA sequences to existing type specimens [@Tautz2003, @Moritz2004, @DeSalle2005, @Goulding2015]. 

Several recent studies have instead created integrative taxonomy protocols for the delimitation of cryptic species, and these share several common features [@Barley2013, @Jorger2013, @Fiser2018, @Singhal2019, @Chaplin2019]. Firstly, all these protocols acknowledge that extensive population sampling along the entirety of a species complex's range is needed to get a clear idea of genetic relationships, gene flow and geographic range limits [@Bernardo2011]. This prevents the inference of spurious splits between populations which, despite appearing genetically isolated, actually represent points along a continuum of genetic variation [@Mason2020]. Next, strong genetic differentiation needs to be demonstrated between putative cryptic species. This differentiation should be shown using data that incorporate independently evolving regions of the genome, to ensure that variation in gene histories from different loci is represented [@Fujita2012]. Commonly used ways of testing genetic differentiation include distance-based methods, where species are delimited only if intraspecific genetic variation is less than interspecific variation [@Puillandre2012], tree-based methods, and coalescent methods [@Leache2014]. Ideally, more than one of these approaches should be used for corroboration. After genetic analysis, morphology should be re-examined to potentially find subtle traits that support the genetic findings [@Barley2013, @Chaplin2019]. Finally, if possible given the distribution of the species complex, reproductive isolation between taxa should ideally be demonstrated through the existence of strongly restricted gene flow between sympatric or parapatric populations [@Singhal2019].  

By reducing the importance of morphological criteria, protocols such as those outlined outlined above, have the potential to call into question the taxonomic validity of subspecies, especially those described before genetic data was widely available. Subspecies are typically defined as morphologically variant, and geographically distinct populations  [@Mayr1982], although geographic isolation is less of an important criteria in plant taxonomy [@Mallet2007]. Historically, any minor morphological pattern or geographic disjunction was considered sufficient to be given subspecific status [@Mayr1982, @Manier2004]. More recently, the rank has been justified in an evolutionary light as a product of microevolution, where population level processes are causing morphological differentiation. Yet, because populations and enviorinments are in flux, this differentiation is not fixed and species level is not warranted [@Tattersall2007]. The formal acknowledgement of the rank is instead useful for conservation [@Haig2006, @Patten2015], and highlights interesting variation that can inform questions on local adaption, migration and dispersal [@Patten2002]. Others argue that metapopulations are where speciation begins [@Levin1995], and subspecies are incipient species which should be recognised as such. Another alternative is that subspecies are well established cryptic species, and the taxonomic bias towards morphology has prevented their description.

Without genetic evaluation, it is impossible to know whether subsp are just localised morphs, incipient species, or well established cryptic species.





The infrageneric taxonomy of the Cape _Ehrharta_ was treated by Gibbs Russell & Ellis (1987), who divided the genus into seven informal species groups. Most of these groups occur predominately in the arid, lower-elevation, renosterveld and succulent karoo vegetation region of the GCFR. There is little taxonomic confusion within these lowlands groups, as the species are clearly morphologically distinct, with characters that easily distinguish the species. Conversely, within two of the three higher-elevation, fynbos-restricted groups, Setacea and Ramosa, the species limits are less clear. The Setacea group consists of two species, _E. setacea_ and _E. rupestris_, the former compromising four subspecies (_disticha, setacea, uniflora_ and _scabra_), while the latter contains three (_rupestris, tricostata_ and _dodii_). As noted by Gibbs Russell (1987), these species and subspecies are morphologically similar and difficult to distinguish. While the subspecies in this group tend to have separate ranges, many of them occur in sympatry in the Caledon area, where intermediates also occur. Species limits are even less clear within the Ramosa group. The group consists of two species, _E. ramosa_ with two subspecies (_aphylla_ and _ramosa_) and _E. rehmannii_ with three subspecies (_rehmannii, filiformis_ and _subspicata_). Gibbs Russell & Ellis (1989) note that "the five taxa comprising the Ramosa group intergrade and few consistently reliable characters adequately separate the species and subspecies". Despite the lack of morphological clarity, they delimited taxa as subspecies based on geographic range and rough morphological "nodes", the taxa in their revisions being based on morphology and anatomy, not genetics (Gibbs Russell & Ellis 1987). While later work by @Verboom2003 used genetic data to infer a phylogeny of Ehrharta, it did not contain population level sampling of the high-elevation groups.

The high-elevation region of the GCFR potentially contains many undiscovered cryptic species, since its archipelagic distribution lends itself to non-ecological vicariant or peripatric speciation [@Verboom2015]. The high- and mid-elevation Setacea and Ramosa groups of _Ehrharta_ are strong candidates for cryptic speciation, as their distributions encompass multiple mountain ranges between which the presence of deep valleys may restrict geneflow, and there a few defining morphological differences between the current taxa. I therefore hypothesize that the subspecies within the high-elevation Ramosa and Setacea groups represent cryptic species that constitute distinct evolutionary lineages. In this chapter, I aim to clarify species limits in these groups using an integrative taxonomic approach [@Dayrat2005]. In order to evaluate the monophyly of these groups and so provide context for their segregation into species, I first present a multilocus phylogenetic tree of the Cape _Ehrharta_ based on genome-wide targeted enrichment data [@Lemmon2012], with population-level sampling of the Setacea and Ramosa groups. In addition to insights obtained from these data, I employ variation in single nucleotide polymorphisms (SNPs) generated through genotyping-by-sequencing [@Elshire2011], and in morphological traits to assess the evolutionary distinctiveness of putative species within these groups.
