---
title: "Discussion"
author: "Lara Wootton"
date: "13/07/2020"
output: 
  pdf_document:
      latex_engine: xelatex
bibliography: Chapt2_refs.bib
csl: harvard-university-of-cape-town.csl
---



# Discussion



The data presented here reveal that, not only are the subspecies within the Ramosa and Rupestris groups likely warrant species status, but that several subspecies can themselves be divided into several coherent taxa. Here, I  

While it is not the aim of this dissertation to present a formal taxonomic revision of the Cape _Ehrharta_, I

- Key results - Most subsp in the Ramosa and Rehmannii warrant species status. Rupestris can be divided further.

- Operational criteria - evidence of genetic isolation between taxa from genetic population assignment analysis (sNMF). Evidence of common ancestry from targeted enrichment phylogenetic analysis. Morphological and ecological differences, sympatry.
- Why do targeted and gbs complement each other?
- Multiple lines of evidence, equals integrative taxonomy
- Species concept de Quiroz - separately evolving metapopulation lineage
- We don't require monophyly, because: Paraphyly is a legit evolutionary process that occurs through anagenesis [@Funk, @Hörandl, @Rieseberg, @Carnicero ] through budding of species
- This isn't a formal revision, rather a basis for future publications

The data presented here suggest that the Rehmannii, Ramosa and Rupestris groups of the Cape _Ehrharta_ each contain multiple species. In particular, there is evidence that the subspecies within the Rehmannii and Ramosa groups warrant species status, and that the Rupestris group potentially contains up to 11 taxa. Here, I discuss the evidence for each species hypothesis, using the unified species concept of @Queiroz2007, where a species consists of a separately evolving metapopulation-level lineage.  The operational criteria used for developing species boundaries in this work are evidence of common ancestry inferred from phylogenetic analysis, evidence of genetic isolation inferred from genetic population assignment analysis (sNMF), as well as evidence of morphological and ecological differentiation. As such, this can be considered an integrative taxonomic approach, as multiple lines of evidence are used to delimit species boundaries. 

Note that these criteria do not necessarily require a species to be monophyletic. Although it is a common taxonomic practice to only recognise monophyletic species, evolutionary processes are able to generate paraphyletic taxa [@Funk2003, @Horandl2010]. During anagenesis speciation, a small population "buds" from the periphery of a species range, rendering the initial species paraphyletic and creating a nested lineage [@Mayr2002, @Crawford2010]. The taxa will eventually reach monophyly, but the rate of lineage sorting depends on factors such as rate of gene flow and population size [@Reiseberg1994, @Funk2003]. Rather than the exception, it has been argued that anagenesis may be a common cause of speciation in plants [@Reiseberg1994]. Therefore, should the two taxa be morphologically or ecologically distinct, it is unnecessary to either sink the budding species or split the initial species just for the sake of retaining monophyly [@Horandl2010, @Kuchta2018, @Carnicero2019]. Other processes that can also result in paraphyly are introgression, hybridisation, and incomplete lineage sorting [@Funk2003], which in of themselves, do not necessarily preclude speciation. @Crisp1995

Although many groups show strong population substructure, not necessarily all diff species - read



## Rehmannii 



The data presented here suggest that the three groups corresponding to the three subspecies of _E. rehmannii_ can each justifiably be considered a species. While Gibbs considered that there to be too many morphological intermediates between the groups to delimit them as species, the data suggest that each group is genetically distinct. The phylogenetic analysis shows that Filiformis group forms a well supported clade, and also displays little admixture with Rehmannii or Subspicata, despite significant range overlap with the latter. Although Filiformis often grows on moist mountain slopes, it was also collected near coastal streams, in one locality in Pringle Bay (1591) growing interspersed with a Subspicata population (1590). The Filiformis group is clearly morphologically distinct, having delicate leaves, thin culms, and few spikelets, which are carried below the leaf level. Filiformis plants also have relatively long glumes and highly striated sterile lemmas. The distribution of the Filiformis group corresponds to that described in Gibbs for *E, rehmannii* subsp *filiformis*, extending from the Cape Peninsula to Agulhas. 

The Subspicata group forms a similarly well-resolved clade, although there is some evidence of admixture with the Filiformis group in the sympatric Pringle Bay locality, suggesting past geneflow or hybridisation. Despite this, the Subspicata group warrants species status based on the clear common ancestry displayed in the phylogenetic analyses, highly different morphology to that of the Filiformis group, and a clear ecological preference for coastal regions. Accession 1660, collected from Agulhas, is somewhat enigmatic. The sNMF analysis assigned it with nearly equal probability to both Subspicata and Filiformis. However, an sNMF run with K = 4 (data not shown), did not assign it to a unique group, and phylogenetic analysis embeds it within the Subspicata group. Its location and intermediate morphology corresponds to the 'limestone' form described in Gibbs. However, as in Gibbs, there is not enough evidence presented here to justify its assignment to a species rank.

There was incongruence between the ML and ASTRAL analyses as to whether the Rehmannii group is a monophyletic group, with the ASTRAL analysis reconstructing the group as grade. Nonetheless, the sNMF analysis showed high levels of admixture within Rehmannii, even at K = 10, suggesting that the group is genetically cohesive. Although similar in morphology to Subspicata, the main differences being in the number of spikelets, relative glume length and the height at which the inflorescence rises above the leaves, Rehmannii has a different range, occurring along the Eastern Langeberg mountains rather than along the coast.    



## Ramosa

There is evidence for three to five species contained within _E. ramosa_. The sNMF analysis did not strongly support the initial hypothesis of three groups (K = 3) based on the phylogenetic analysis, as it showed admixture between the Aphylla and Western Ramosa groups. However, given the genetic disparity displayed within the Western Ramosa group (PCoA), it is likely the sNMF analysis with K = 8 is a more trustworthy result.

The Aphylla group is well supported as a potential species, as not only is there clear common ancestry shown in the phylogenetic analysis, but both the sNMF analysis at K = 8 and PCoA show strong genetic similarity between populations within the group. The Aphylla group is also morphologically different from the rest of the Ramosa clade, with a greater relative glume length, longer leaves, fewer spikelets and often striated sterile lemmas. However, the group has a restricted range compared to that of _E. ramosa_ subsp. _aphylla_ in Gibbs, only consisting of populations from the Cape Peninsula to Betty's Bay. The Eastern Ramosa group occurs along the Swartberg and Langeberg mountain ranges, and can potentially be considered a species as it exhibits strong genetic similarity between populations (PCoA), and is recovered as monophyletic in the ASTRAL tree. Most populations in Eastern Ramosa are assigned with moderate probabilty to an ancestral genepool not present in Aphylla or Western Ramosa at K = 3, supporting the Eastern Ramosa groups distinctness from the two. Although an LDA based on morphology separates Eastern Ramosa from Western Ramosa with only a few individuals misclassified, there is no single trait that clearly distinguishes this group from the rest of the Ramosa clade.  

The Western Ramosa group is distributed across the *** mountains, and is likely to consist of two or more species, as there is considerable genetic and morphological heterogeneity within the group. Two accessions from Milner Peak (1622, 1624) show no admixture, despite occurring within a few kilometres of each other, suggesting that they may be different biological entities. Similarly, sympatric accessions from Limietberg (1609, 1611) are not recovered as sisters in the phylogenetic analysis. However, the sampling density of this study is not sufficient infer the species limits of these potential taxa, therefore I err on the side of caution and do not recommend splitting this complex further. Instead, I recommend that the Western Ramosa group is treated as a single species, as it is monophyletic in the ML analysis, and in the ASTRAL analysis paraphyletic only with regards to the Aphylla group, in addition to it an LDA showing that is morphologically distinguishable from the other Ramosa groups. 





While there is some evidence for common ancestry, as the group is monophyletic in the ML tree, (but a grade in the ASTRAL tree), the PCoA shows greater within population similarity than within group similarity, and the sNMF analysis reveals addition subdivisions within the group. For example, two accessions initially identified as *E. ramosa* subsp. *aphylla* from Milner Peak (1622) and Limietberg (1609), are recovered as sisters in the phylogenetic analysis, and show high levels of admixture with each other, but not with a sympatric Milner Peak *E. ramosa* subsp. *ramosa* accession (1624). Similarly, in Limietberg, the *E. ramosa* subsp. *ramosa* accession (1611) is not recovered as sister to the *E. ramosa* subsp. *aphylla* (1609) accession growing in sympatry. However, an LDA analysis including the two accessions as a separate group was unable to clearly differentiate them from the remaining Western Ramosa populations on the basis of morphology (data not presented). Similarly, another potential species is the Milner Peak *E. ramosa* subsp. *ramosa* accession (1624) which genetically distinct from all other Western Ramosa populations. Nonetheless, I recommend that Western Ramosa be treated as a single species until further sampling can be done on the group The question is then, do the remaining Western Ramosa accessions form a cohesive species, or would further fine-scale sampling find evidence for more subdivisions? 



## Rupestris

Gibbs described two species and seven subspecies within the Rupestris clade, the majority of which were found to be polyphyletic in this study. As such, the Rupestris clade potentially contains between nine and eleven species, largely corresponding to the groups recovered in the phylogenetic analysis. *E. rupestris* subsp. *rupestris* was found to consist of two lineages, the Eastern and Western Rupestris groups, which were not resolved as sisters in the phylogenetic analysis. Western Rupestris comprises the "typical" form of  *E. rupestris* subsp. *rupestris*, and the group's formation of a well-resolved monophyletic clade, together with intra-group admixture at K = 9, and a divergent genetic composition strongly support its promotion to species status. Eastern Rupestris corresponds to the smaller form of *E. rupestris* subsp. *rupestris* mentioned in Gibbs, which occurs along the Swartberg mountain ranges. The species status of this group is supported by internal admixture and a highly dissimilar genetic composition to the rest of the Rupestris clade. However, the morphology of the two Rupestris groups is highly similar, the Eastern group having slightly finer leaves and culms. The ecology of the two is also subtly different, with W. rupestris occurring on mountain summits, and E. Rupestris collected on moist lower slopes. 

The Uniflora group, corresponding to _E. setacea_ subsp _uniflora_, had both a distinct genetic composition and a unique morphology, clearly showing that it is a species in its own right. The group is characterised by thin leaves and culms, with long-glumed, small spikelets. Similarly, the phylogenetic analysis shows that the Restiod Tricostata group forms a well-supported clade, with little admixture with groups also deemed in *E. rupestris* by Gibbs, although there is some similarity with the Fernkloof group.  The Restiod Tricostata group also has one of the most distinctive morphologies in the Rupestris clade, with clear separation in the LDA. Univariate analyses show that it is characterised by large internode distances, highly reduced pedicels, and sheaths that are long relative to leaf length. This group occurs in seeps from the Cape Peninsula to Hermanus. 

There is some evidence that the Fernkloof group recovered in the phylogenetic analysis may consist of two species. One of these potential species, called here Fernkloof A, would consist of the *E. setacea* subsp *disticha* accessions from Buffelstalberg (1589) and Fernkloof (1597, 1598),  and two other Fernkloof accessions, one a small statured accession that appeared to be an intermediate form between *E. setacea* subsp *disticha* and *E. setacea* subsp *setacea* (1599), and a larger form that had a creeping growth habit (1593). The other potential species, Fernkloof B, would consist of two accessions with a morphology similar to that of the Setacea group (1595 and 1600). The primary evidence to recognise these two groups a distinct species is that there appears to be little to no admixture between them, despite occurring in sympatry within the Fernkloof Nature Reserve. There is also evidence of morphological differentiation, as Fernkloof B has substantially longer spikelets, leaves, and thicker culms, in addition to some indication of ecological differentiation, with Fernkloof A collected on rocky slopes, and Fernkloof B in marshy seeps.

The Scabra group corresponds to Gibbs conception of *E. setacea* subsp. *scabra*. Unexpectedly, a Scabra population from Marloth (1633) showed high levels of admixture with other groups at K = 9, particularly with the Leafy Tricostata gene pool, although at K = 19 this effect disappeared. However, there was very little admixture with the Setacea group the occurs in sympatry. In addition, due to its morphological distinctness, and monophyly recovered in the phylogenetic analysis, I recommend that the Scabra group be given species status. An accession originally identified as *E. rupestris* subsp. *tricostata* (1640) is recovered as sister to the remainder of the Scabra group, and corresponds to the Scabra individuals misclassified in the LDA plot. It is possible that this accession should not be included within the larger Scabra group, but as it was not included in the sNMF analysis, there is not enough evidence to justify the split.

The data also suggest that the Setacea group can be considered a species. The group consists of a monophyletic clade in the ASTRAL tree, has stronger admixture and genetic similarity between populations than with other species groups. While its morphology is somewhat variable, and overlaps with that of the Fernkloof groups, it still forms a relatively cohesive cluster within the LDA. In particular, the group is distinguished by glumes of approximately the same length as the lemmas. The Setacea group is one of the most widespread in the Rupestris clade, occurring in moisture-rich habitats from the Cape Peninsula, to Limietberg and to Marloth. 

The Leafy Tricostata and Dodii groups have a similar morphology, mainly differing in the number of spikelets. Nonetheless, genetic data suggest that they are separate species, as they form separate monophyletic clades in the ASTRAL analysis, the PCoA shows little similarity between the two groups. Finally, the accession 1657, collected from Wemmerhoek and initially identified as *E. rupestris* subsp. *tricostata*, is another potential species. Poorly resolved in the phylogenetic analysis, it shows no admixture with any other species groups, and has a morphology intermediate between that of the Setacea and Leafy Tricostata groups. 



## Crypticity in the Cape Ehrharta



The potential new taxa hypothesised above increase the number of species in the Cape _Ehrharta_ by 15, from 22 to 35, with the number of species in the Rehmannii, Ramosa and Rupestris clades together now nearly equaling that of the Lowlands clade. Of these, there are several cryptic or semi-cryptic taxa. It was expected that the predominantly high-elevation Rupestris clade would show the greatest signature of cryptic speciation, due to isolation of populations on the peaks of the heterogeneous Cape Fold Mountains. The Setacea and Fernkloof B groups are perhaps the strongest example of this, as they are clearly genetically distinct, but have a nearly identical morphology and habitat preference. The Dodii and Leafy Tricostata, and Eastern and Western Rupestris groups might better be described as semi-cryptic, as there are subtle morphological differences. The cryptic species pairs in Rupestris are all allopatric with respect to each other, suggesting isolation by topology may be driving their divergence. Nonetheless, other species in the clade, such as the Restiod Tricostata, Uniflora, and Scabra groups are easy to distinguish, implying some role of ecological processes in the diversification of this clade. More surprising were the high levels of crypticity in the Ramosa clade. Thought to have a higher tolerance of aridity than the Rupestris clade, it was expected to be able to traverse dry valleys with more ease. Instead, strong population structure within each potential Ramosa species suggests that the taxa experience limited geneflow. It is unclear whether this is a function of topology or of a biological characteristic such as poor dispersal or vegetative growth. 



## Patterns of gene exchange and radiation

The species richness of the mid- and high elevation clades calls into question our understanding of the evolutionary history of _Ehrharta_. @Verboom2003 found that the species richness of the genus was generated from a single lineage within _Ehrharta_, that corresponding to the Lowlands Clade, which underwent an adaptive radiation event within the Cape winter-rainfall zone in response to increased aridity and rainfall seasonality during Late-Miocene climate change [@Verboom2003, @Verboom2004]. Instead, the evidence presented here suggests that both Rupestris and Ramosa-Rehmannii clades have also undergone appreciable diversification. While the Lowlands clade shows clear trait optimisation in response to climatic and edaphic properties [@Verboom2004], neither the Rupestris nor Ramosa clades show the trait disparity expected by an adaptive radiation (ref). It is possible that the Rupestris and Ramosa clades are still in the early stages of speciation, and that morphological diversification is lagging behind genetic differentiation [@Kaefer2012]. Alternatively, the clades may be undergoing a non-adaptive radiation. Defined as lineage diversification with minimal ecological diversification, non-adaptive radiations typically result in allopatric or parapatric taxa [@Rundell2009]. 



What could be causing their radiation? Rundell says ecologically similar and allopatric likely to be non adaptive. This fits Ramosa in particular, as well as groups within Rupestris, eg dodii and leafy, Setacea, fernkloof B, and W rup Fern A. Rupestris and probably Ramosa follow Levyns Law, with a greater concentration of species in West. Is the greater topological fragmentation causing speciation? sNMF shows geneflow along langeberg, ed leaf trico, E ramosa, more pop structuring in West.  Weird how arise almost simultaneously, but must have been triggered by something bse such short branches.

Early in the speciation process - genetic divergence before phenotype eg @Kaefer2012

Strong stabilising selection

Non adaptive



## Critique of species concept and data, plus other clades

There has been considerable criticism over the validity of cryptic species, including that they are artefacts of new species concepts, that genetic data is insufficient to delimit distinct evolutionary units, and that delimiting cryptic species is contributing to taxonomic inflation, disrupting established taxonomy and hindering conservation efforts [@Tattersall2007, @Isaacs2004, @Mace2004, @Heller2013]. Most argue that morphology should be the primary character for species delimitation, as it is a proxy for reproductive isolation (ref), and that careful investigation will find morphological differences if the species is valid [@Korshunova2019]. Yet not only can morphology be heavily influenced by environmental conditions, increasing the noisiness of its phylogenetic signal, but genetic data are a more direct measure of reproductive isolation [@Bernado2011] and allow for a greater understanding of the processes driving historical and contemporary speciation pattens [@Georges2018]. Nonetheless, in order to alleviate the fear that genetic data increases Type 1 error rate, where the rank of species is assigned to a population [@Cotterill2014], this study uses two lines of genetic evidence with difference resolutions to delimit species, which taken together, provide a robust picture of species boundaries. Few other studies have conducted such geographically thorough, population-level genetic evaluations of species boundaries within the GCFR, notable exceptions being @Schaik2020, @Britten2014, @Rymer2010, @Prunier2010, @Prunier2017, @Lexer2014. Of these, several found evidence for cryptic species, suggesting that there may be substantially more biodiversity in the GCFR than currently thought, particularly within lineages that are widespread throughout the mid- and high-elevation zones.  

#### Conclusions

We have found several new potential species. 

Probably not solely topography







