---
title: "Intro"
author: "Lara Wootton"
date: "11/08/2020"
output: html_document
---



# What is driving speciation in the cape?

Adaptive radiation – the rise of a diversity of ecological roles and attendant adaptations in different species within a lineage

Lineage diversification is often accompanied by a variety of new ecological roles [@Givnish1997; @Givnish2015]. Known as adaptive radiation, this phenomenon is driven by divergent selection between closely related, ecologically-similar species.

a exploitation of a diverse ecological niche origin of a wealth of ecological roles in species within 

New environments or the evolution of key traits can trigger a burst of speciation, as new niches are exploited. Known as adaptive radiation, this phenomenon is perhaps the most widely invoked explanation for lineage diversification. a pattern of species diversification in which newly arisen species occupy a diversity of ecological roles  where a new habitat or evolution of a new trait ecological speciation, natural selection.  Non-adaptive radiation occurs when lineages diversify with little ecological divergence [ @Czen.]. It often arises due to the restriction of gene flow by a geographic barrier, resulting in allopatric or parapatric taxa  [@Gittenberger1991; @Rundell2009]. With limited to nonexistent gene flow, genetic drift allows populations diverge and speciate via the random fixation of alleles. Adaptive and non-adaptive radiation events are expected to leave different morphological and genetic patterns within their descendent lineages. Due to the role of natural selection, lineages diversifying by an adaptive radiation typically have substantial morphological and ecological variation, as well as elevated rates of morphological and genetic change. Conversely, non-adaptive radiation events often result in species that are poorly morphologically differentiated, and that have approximately neutral rates of genetic evolution. 



Adaptive radiation, driven by ecological speciation, is undoubtedly an instrumental force in generating the high species richness of the GCFR. Ecological speciation occurs when barriers to gene flow evolve among populations due to ecologically-based divergent selection [@Schluter2009; @Rundle2005]. The rugged topography of the Cape provides strong environmental gradients, which together with fine-scale edaphic mosaics, promote adaption to local selection pressures, driving ecological shifts between closely related species [@Vanderniet2009]. Many of the iconic GCFR radiations, such as _Erica_, _Protea_, _Phylica_, _Muraltia_, _Pelargonium_ and Aizoaceae, are thought to have ecological components, whether that be shifts in climate or edaphic preference, pollinator syndrome or fire-survival strategy [@Richardson2001; @Forest; @Schnitzler2011; @Klak2004; @Pirie; @Vanderniet2014]. However, early researchers in the Cape theorised that the mountains played an altogether different role in fostering speciation. @Adamson 1958 and @Goldblatt 1978 speculated that high elevation communities were a relics of a previously widespead flora that contracted upslope in the face of an increasingly arid climate, resulting in vicariant species. Although considerable variation in the timing of high-elevation divergence events contradicts the idea of a simultaneous vicariant speciation event, the hypothesis of non-adaptive speciation, driven by isolation-by-distance, in explaining high-elevation diversity has recently regained traction [refs]. Montane clades in the Cape often show strong allopatry and small ranges, with sister species occupying comparable niches [@Verboom2015], which are characteristic of non-adaptive radiations [@Rundell2009]. Crucially, there is also evidence for diversification within ecologically-similar elevational bands, suggesting that factors other than ecological divergence are contributing to the species richness of the Cape [@Verboom2015].    

Adaptive and non-adaptive radiation events are expected to leave different morphological and genetic patterns within their descendent lineages. Due to the role of natural selection, lineages diversifying by an adaptive radiation typically have substantial morphological and ecological variation, as well as elevated rates of morphological and genetic change. Conversely, non-adaptive radiation events occur via neutral processes  such as genetic drift, often resulting in species that are poorly morphologically differentiated, and that have approximately neutral rates of genetic evolution. In order to distinguish between the two radiation types, rates of morphological change can compared between clades, either by hypothesising _a priory_ where a rate shift occurs in the tree [@OMeara] or by modelling potential shift locations [@Eastman]. In addition, the strength and direction of natural selection between clades can be evaluated by comparing the ratio of non-synonymous (dN) to synonymous (dS) substitutions (dN/dS = $\omega$) in protein-coding genes. A non-synonymous substitution is a mutation that changes an amino acid within a protein, and can therefore experience selection, while a synonymous substitution does not cause changes to the protein, allowing their accumulation at the same rate as the overall genomic mutation rate [@Kimura1968]. However, determining $\omega$ is a non-trivial matter, as it can vary over time, between sites and between lineages [ref]. While there are both heuristic (ref) and Bayesian [@Angelis2014] (see book) methods of estimating $\omega$, maximum likelihood methods, such as those implemented in codeml, are widely used as they are able to flexibly account for both transition–transversion rate differences and unequal codon frequencies.



Different lineages may be inherently predisposed to one a speciation type [protea paper, rundel2009 for bird example]. Latimaer2009 found no home ground advantage 

 poorly dispersed CFR Proteaceae occupy less of their predicted potential ranges than well-dispersed species (Schurr et al. 2007).



*Particularly clades with poor dispersal, poor plasticity, moisture needs, old clades, phylogenetic niche conservatism etc life history 



The Lowlands clade of the Cape _Ehrharta_ experienced accelerated speciation during the Late Miocene. The rapid radiation had a strong ecological component, associated with the lineage's transition into the Succulent Karoo. While the early lineages of the Cape _Ehrharta_ are restricted to Table Mountain sandstone,  Succulent Karoo taxa have adapted to a variety of soils, including granite (_E. barbinodis_ and _E. pusilla_), coastal dunes (_E. villosa_) and shale (eg. _E. melicoides_ and _E. eburnea_). As expected in an adaptive radiation, the Lowlands clade exhibits substantial morphological variation, particularly in floral traits, growth form, and life history []. The Lowlands radiation was thought to be the only diversification event within the Cape _Ehrharta_, tying in with the narrative that the majority of GCFR radiations are based on ecological speciation. However, this study provides evidence for multiple new species occurring in the mid- and high-elevation Ramosa and Setacea clades, which suggests that there may have been more than one diversification event in the Cape _Ehrharta_. The cryptic nature of the new species hints at the possibility of a non-adaptive radiation driven by geographic isolation on the archipelagic peaks of the Cape Fold mountains.  



The aim of this chapter is to present a dated, species-level phylogenetic hypothesis, and to use this as a framework for estimating and comparing rates of diversification, phenotypic and $\omega$ evolution between high-, mid- and low-elevation clades. It is hypothesized is that stronger population isolation paired with a more uniform selective regime increases the influence of neutral processes as a driver of differentiation at high elevations. As such, I predict lower rates of phenotypic evolution and lower $\omega$ in the high-elevation Setacea clade relative to the Ramosa and Lowlands clades.





However, the structure of many species distributions in the GCFR also fit the model of. The region is characterised by extremely high levels of species turnover and local endemism, rather than the more uniform alpha diversity that define other biological hotspots such as tropical rain forests. Many species have small ranges, and are geographically replaced by closely related, often ecologically similar species. Within a species, populations are often fragmented due to topographical barriers, and poor seed dispersal (many Cape species dispersed by ants) resulting in low migration rates. This fits with predictions of neutral theory, which states that low migration systems should have high beta diversity, while allopatric distributions, as found in the Cape, can be a signature of non-adaptive radiation. Initial researchers in the While undoubtedly  Cape has a mixture of the two, the importance of non-adaptive is perhaps understated. There is evidence of within-elevational band diversification, which is significant as elevational bands are likely to be ecologically similar, potentially suggesting neutral speciation, as opposed to diversification along elevational gradients, which have a wide range environments. Since by definition adaptive radiations generate morphologically divergent species, there may be a taxonomic bias towards description of morphologically varied taxahides importance of non adaptive



How can you test for non adaptive vs adaptive?



A characteristic of the fynbos is high species turnover, poor dispersal, fragmented populations, small ranges.

The pattern is predicted by both neutral and adaptive radiations

Main difference could be rates of genetic and phenotypic change, and ecological differentiation. Neutral radiations, occurring through drift,  slower genetic and phenotypic change. Many examples of strong trait disparity and adaption - ericas, lowlands, also cryptic radiations (although have their morphological rates been quantified?)

Speciation within elevational bands suggests neutral

 ecological speciation is largely or mainly the result of divergent selection to different niches of organisms, and ecological interactions such as competition, predation or parasitism drives the evolution of reproductive isolation. Its importance is exaggerated Svensson 2012







How does neutral vs selection change rates?



Affects of small popsize on rate?



How do you compare rates of evolution? 

* a priory hypotheses
* Shift simulation



How does disparity differ from rates



phenotypic change not necessarily linked to genotype change @davies2006

## DNDS



What is omega? 

* Define dN, dS and omega

* useful measure of the strength and mode of natural selection acting on protein-coding genes @2015 book
* If >1, indicates positive selection, =1 neutral evolution, <1 purifying selection.  @2015 book, @Yang and nielsen2002
*  



Why is it relevant? 

* Identifies genes or sites that are conserved or have undergone selection @2015 book
* Adaptive radiations with phenotypic change imply genetic change @Weadick 
* test hypotheses about the relative effects of selection in certain lineages of interest @delatorres, @Nielsen2005



How is it measured?

* Pairwise, branches, sites, clades
* Branches and sites more powerful than pairwise @delatorres
* Branch model ref Yang Z, Nielsen R: Synonymous and nonsynonymous rate variation in nuclear genes of mammals.
* Clade models [19,20], meanwhile, can be used to detect more subtle differences in site-specific selective constraint among entire clades or partitions of a phylogeny @Weadick
* Branch models [65] assume that the ω ratio varies across branches of the phylogeny (specified a priori) but that it is invariant across sites of the alignment; comparing complex Branch models (i.e., ones with multiple ω ratios) against simpler, nested models tests whether ω varies significantly between sections of the phylogeny. Since Branch models make the unrealistic assumption of among-site homogeneity, they often lack power to detect subtle patterns of divergence across phylogenies, @Weadick

 What are its drawbacks? 

Model assumptions,

Local peaks



The strength and direction of natural selection on protein-coding genes can be measured using the ratio of non-synonymous to synonymous substitutions ($\omega$). A non-synonymous substitution is a mutation that changes an amino acid within a protein, and can therefore experience selection, while a synonymous substitution does not cause changes to the protein, allowing their accumulation at the same rate as the overall genomic mutation rate [@Kimura1968]. Consequently, if the rate of non-synonymous substitutions is higher than synonymous substitutions ($\omega$ > 1), there is evidence that the protein is experiencing positive or adaptive selection, if the two rates are equal ($\omega$ = 1), the protein is evolving neutrally, while if $\omega$ < 1 it suggests that non-synonymous substitions are deleterious and the protein is likely undergoing purifying selection. By Identifying genes and sites that have undergone selection, $\omega$ allows testing of evolutionary hypotheses, such as how different environmental pressures affect adaptation [@Mohandesan2017], and how genetic change underpins radiation events [@Weadick2012]. However, determining $\omega$ is a non-trivial matter, as it can vary over time, between sites and between lineages. While there are both heuristic (ref) and Bayesian [@Angelis2014] (see book) methods of estimating $\omega$, maximum likelihood methods, such as those implemented in codeml, are widely used as they are able to flexibly account for both transition–transversion rate differences and unequal codon frequencies.  



Within the Cape _Ehrharta_, ecological speciation is an important aspect in the diversification of the Lowlands clade, where a transition from Fynbos into the Succulent Karoo stimulated a rapid radiation in response to new edaphic niche space [@Verboom2004]. 

The aim of this chapter is to present a dated, species-level phylogenetic hypothesis, and to use this as a framework for estimating and comparing rates of diversification, phenotypic and $\omega$ evolution between high-, mid- and low-elevation clades. It is hypothesized is that stronger population isolation paired with a more uniform selective regime increases the influence of neutral processes as a driver of differentiation at high elevations. As such, I predict lower rates of phenotypic evolution and lower $\omega$ in the high-elevation Setacea clade relative to the Ramosa and Lowlands clades.