---
title: "Discussion"
author: "Lara Wootton"
output: 
  pdf_document:
      latex_engine: xelatex
bibliography: Chapt2_refs.bib
csl: harvard-university-of-cape-town.csl
fontsize: 12pt
linestretch: 2
---

\raggedright
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



The hypothesis that neutral processes are relatively more important as a driver of differentiation at high elevations. There is little indication of accelerated diversification within Succulent Karoo or Lowlands clades, although there is limited evidence for elevated diversification rate within the Setacea clade. 

 In addition, the rate of morphological change showed the opposite pattern to that predicted, with elevated rates of change in _Setacea_, rather than in the Lowlands clade. Similarly, the strongest signal of positive selection was shown in the Setacea clade. It appears that diversification in both the Lowlands and Setacea clades has been influenced to a greater extent by ecological speciation, while non-ecological speciation may be more important in the mid-elevation Ramosa-Rehmannii clade. 

Establishing age estimates for lineages within Poaceae has been hindered by a scarcity of macrofossils [@Stromberg2011], leading @Prasad2011 to make use of phytolith microfossils ito calibrate their phylogenetic tree of Poaceae. The resulting age estimates of @Prasad2011, which were used here to calibrate both the *Oryza*-*Ehrharta* (72.5 Ma) and *Ehrharta*-*Microlaena* splits (20 Ma), generally exceed previously published age estimates for these nodes (see below). Consequently, the age estimates presented in this study for nodes within *Ehrharta* lie at the older end of the range of possibilities suggested by previous higher-level dating analyses. For example, in contrast to the 72.5 Ma estimate of @Prasad2011, @Vicentini2008, @Bouchenak2010, and @Hoffmann2015 dated the *Oryza*-*Ehrharta* split at 35, 50 and 25 Ma respectively, while Bouchenak-Khelladi et al. (2010) also estimated the *Ehrharta*-*Microlaena* split at 10 Ma. Rescaling the trees obtained in this study, using these alternative dates for the *Oryza*-*Ehrharta* divergence, substantially alters the ages of key clades within *Ehrharta* (Table 4), which has implications for understanding the context in which their diversification took place.

The older date estimates suggested by the Prasad et al. (2011) calibrations are difficult to align with current understanding of the climatic, geological and vegetation history of the GCFR. In particular, the results place the origin of the Succulent Karoo clade in the Mid-Miocene, which antedates the onset of a summer-arid climate during the Pliocene [@Dupont2011; @Hoffmann2015] and the origin of the Succulent Karoo vegetation type itself [@Verboom2009]. Rescaling the dates presented here, using alternative estimates of the timing of the *Oryza-Ehrharta* split (Table 4), however, places the crown age of the Succulent Karoo clade between 10.6 and 5.3 Ma, which coincides with the suggested timing of the radiation of the succulent karoo flora [@ref].



 The present study used the dates of @Prasad2011 as calibration, resulting in age estimates which, at 68 Myr for _Oryza_ - _Ehrharta_ and 20 Myr for _Ehrharta_ - _Microlaena_, are substantially older than previous estimates for the origin of _Ehrharta_. For example, @Hoffmann2015, @Vicentini2008 and @Bouchenak2010 dated the split between _Oryza_ and _Ehrharta_ at 25, 35 and 50 Ma respectively, while @Bouchenak2010 also estimated _Ehrharta_ - _Microlaena_ at approximately 10 Ma. The older date estimates with the @Prasad2011 calibrations are difficult to contextualise given the climatic history of the GCFR. The results place the origin of the Succulent Karoo clade during the Mid-Miocene, predating the onset of a summer-arid climate during the Pliocene [@Dupont2011] and the origin of the Succulent Karoo vegetation type itself [@Verboom2009]. Similarly, the moisture-loving Setacea clade would originate and diversify during the arid Pliocene. Rescaling the dates presented here with the age estimates of @Vicentini2008, @Bouchenak2010 and @Hoffmann2015 would place the crown age of the Succulent Karoo clade between 10.6 and 5.3 Ma, coinciding with the origin of the Succulent Karoo flora, and the crown age of the Setacea clade between 3.7 and 1.9 Ma  (Table 4), coinciding with the cooler and wetter Pleistocene. Given the difficulty of assigning microfossils to a particular lineage [@Christin2014], and the lack of concordance with previous studies, the absolute dates in this work should perhaps be interpreted with caution. Nonetheless, as the branch length relationships would remain the same regardless of their absolute time calibrations, changes in date estimates would not alter downstream analyses of morphological and molecular evolution.         

Overall, diversification within Cape *Ehrharta* appears to have occurred at a relatively constant rate, albeit with some evidence of accelerated diversification within the Setacea clade. This inference holds both for trees containing all species- and subspecies-level taxa included in Cape *Ehrharta* and for trees pruned to contain only those taxa considered by @Verboom2003. A uniform diversification rate scenario is inconsistent with the findings of @Verboom2003 and @Hoffmann2015, who identified a rapid increase in diversification rate on the branch leading to the Succulent Karoo clade. The inconsistency may be an artefact of the DNA marker choice, since the dating inferences of both @Verboom2003 and @Hoffmann2015 were based on just two markers, ITS and trnL-trnF, in contrast to the inferences presented here which are based on multiple marker sets, each comprising 50 loci. Alternatively, failure to retrieve a diversification rate shift at the base of the Succulent Karoo clade may reflect the omission of the non-Africa genera, *Microlaena*, *Tetrarrhena* and *Petriella*, which may have reduced the power to detect rate shifts across the tree [e.g. @Guyer1993; @Agapow2002]. However, uniform or even decreasing diversification rate is a common phenomenon in the Greater Cape flora, with clades such as Restionaceae [@Linder2004; @Bouchenak2017] and _Leucadendron_ [@Hoffmann2015], showing a steady accumulation of lineages over time, and others, such as _Protea_, _Moraea_ and _Tetraria_ showing diversification slowdowns [@Schnitzler2011; @Slingsby2014; @Hoffmann2015]. These patterns are generally attributed to low extinction rates [@Cowling2002; @Linder2005; @Linder2008; @Valente2010], associated with climatic buffering during the Pleistocene glacial cycles [@Colville2020; @Dynesius2000]. The southwestern GCFR, where the majority of Lowlands and Succulent Karoo clade taxa occur, is thought to have been particularly stable for long periods of time [@Colville2020], potentially facilitating the slow and constant accumulation of species in the Lowlands clade. In the mid- to high-elevation lineages of Cape *Ehrharta* (Setacea, Ramosa-Rehmannii and Dura clades), however, the relative recentness and sudden emergence of contemporary species diversity, which together produce a “broom and handle” tree shape, is suggestive of high rates of extinction [@Nee1994; @Crisp2009]), and it is possible that these lineages, of which almost all extant taxa are moisture dependent, underwent substantial extinction with the onset of drier conditions in the Late Miocene-Pliocene [@Buerki2012].

Adaptive radiations are expected to generate high levels of morphological variance between taxa, as the lineages differentiate to fill available niche space [@Schluter2000]. The Lowlands clade, predicted to display the strongest signature of adaptive evolution, did indeed show considerable trait variation, especially in comparison to the Setacea clade. Despite the difficulty of directly inferring a causal link between adaptive processes and trait variation [@Mitchell2015; @Reich2003], @Verboom2004 were able to show that the trait values in the Lowlands clade do indeed reflect adaptation to heterogeneous environmental conditions. This result is corroborated by elevated rates of functional trait evolution (leaf length, plant height, lemma length and spikelet size, the latter being a proxy for seed size) in the Lowlands clade in comparison to the rest of the tree, reflecting divergent selection on traits necessary for survival [@Cornelissen2003; @Jardine2020]. Conversely, the lower levels of trait variation in the Ramosa-Rehmannii and Setacea clades is consistent with non-adaptive speciation [@Rundell2009]. Absolute trait variance, however, does not take into account evolutionary time, and it is possible that young clades under strong selection may not have had sufficient time to differentiate, potentially hiding support for ecological speciation. This may apply to the Setacea clade which, despite showing generally low trait variance, exhibiting substantially higher rates of evolution for most phenotypic traits, when compared to the rest of the tree. In contrast, the Ramosa-Rehmannii clade showed striking levels of conservatism in almost all traits, relative to the rest of the tree, suggesting that this clade is under strong stabilising selection or at least has not responded to strong diversifying selection [@Losos2008]. This interpretation of the morphological rate results is, however, contingent on the assumption that trait divergence happens gradually and continuously. Should evolution in these clades follow the punctuated equilibrium model of speciation [@Gould1993], where pulses of morphological change are followed by long periods of stasis, then the comparisons of absolute trait variance may be the more appropriate measure of adaptive divergence [@Mcentee2018]. 

None of the clades displayed a signature of positive selection ($\omega$ > 1). This is unsurprising, however, since the branch models used in this study estimate $\omega$ as an average rate across all sites [@Yang2007] and the loci sampled are likely to be conserved [@Johnson2019]. Nonetheless, it is still informative to use such models to compare $\omega$ between clades in order to evaluate relative strength of selection [@Delatorres2017; @Buschiazzo2012]. The Setacea clade displayed the highest value of $\omega$ (Setacea clade $\omega$ = 0.23, background $\omega$ = 0.18), therefore showing the strongest evidence for divergent selection. Although this is contradicts the hypothesis of speciation being non-adaptive speciation at high-elevations, it is in accordance with the elevated rates of phenotypic evolution observed in the Setacea clade. The Ramosa-Rehmannii clade also showed a slightly higher value of  $\omega$ compared to the rest of the tree ($\omega$ = 0.21 vs  $\omega$ = 0.19), but this was likely the consequence of a large positive outlier corresponding to Eastern Ramosa (Fig. free_ratios). Surprisingly, although the Lowlands clade displayed higher rates of sequence evolution (dS and dN) than the Setacea and Ramosa-Rehmannii clades, possibly as a consequence of a prevalence of short-lived annual and weak perennial species in the clade [@Smith2008rates; @Verboom2012], it displayed the weakest evidence of positive selection, yielding the lowest estimates of $\omega$. This result is unexpected given the high phenotypic variance of this clade, as well as the inferred adaptive mode of its radiation [@Verboom2004]. While it is possible that there has been very little divergent selection within the clade, and that the observed trait variance is due to neutral divergence over long periods of time, this seems unlikely given the affinity of Lowlands taxa to their local substrates [@Verboom2004]. Alternatively, the analyses used here are insufficiently sensitive or comprehensive enough to find evidence of divergent selection in the clade. For example, selection pressures act heterogeneously across the genome [@Wolf2009; @Kunstner2010], and the 44 loci sampled here are most likely not representative of the genome as a whole. Additionally, divergent selection on just one or two amino acid sites can make a substantial difference to protein function, and this signal is easily lost when using averaged values of $\omega$ [@Yang2007; @Weadick2012].

Therefore, the results of this study suggest that, while radiation mode does vary between clades of  Cape _Ehrharta_ does vary between clades, the relative influence of divergent selection does not decline as a simple function of increasing elevation as hypothesised by @Verboom2015. While the Lowlands clade does appear to have diversified via an adaptive radiation, with changes in life history and growth form (e.g. annuals, geophytes) providing access to arid environments previously unavailable to _Ehrharta_ [@Verboom2004], this diversification was not explosive [@Givnish2015]. Rather, the Lowlands clade seems to have diversified over an extended period, with new species evolving episodically to fill the diversity of niches at low elevations, and low rates of extinction fostering the high standing diversity of the clade [@Dynesius2000]. Under some definitions, this is nonetheless considered adaptive radiation [@Givnish2015]. In contrast, the mid-elevation Ramosa-Rehmannii clade is the radiation least likely to have been powered by adaptive divergence. Species in the Ramosa clade occur in similar habitats, consisting of dry, rocky slopes in the fynbos, which, together with limited morphological differentiation, suggests a minimal role for divergent adaptation in their diversification. Instead, low levels of seed set (_pers. obs._), potentially limited dispersal ability and reliance on clonal reproduction may make the precipitous Cape mountains and deep shale valleys an effective barrier to gene flow in this group [@Givnish2010; @Kisel2010]. Similarly, although Rehmannii species have undergone some ecological differentiation, with Subspicata favouring coastal habitats, Rehmannii forest margin habitats and Filiformis damp sites in fynbos, the limited range overlap shown by these species suggests that speciation may originally have been allopatric and potentially nonecological. Finally, the high rates of phenotypic and genetic change shown by the high-elevation Setacea clade suggest that the radiation of this clade has almost certainly involved a substantial ecological component, with the semicryptic nature of some species potentially being a consequence of the recentness of this radiation. There also appears to be strong ecological differentiation within the clade, for example, Western Rupestris occurs on rocky ridges on mountains peaks, Setacea favours seepages, Uniflora is almost hydrophytic in swamps, Dodii grows beneath wet cliffs, and Fernkloof A prefers rocky slopes. It is difficult to pinpoint the exact trigger of diversification in the Setacea clade given the uncertainty in the age estimates. However, it is possible that climate oscillations during the Pleistocene may have been a contributing factor, as many montane clades have undergone substantial diversification during this epoch, with the fluctuating climate causing suitable habitat to expand and contract along mountain slopes, altering population connectivity and gene flow patterns[@Muellner2019; @Mairal2017; @Flantua2018].  

Substantial effort has gone into understanding and predicting patterns of radiation in the GCFR [eg @Linder2004; @Linder2008; @Vanderniet2009; @Schnitzler2011; @Verboom2015; @Bouchenak2017]. It is clear that the evolutionary history of the Cape flora is complex, with a range of climatic, geological and historical events influencing diversification [@Cowling2002; @Linder2015; @Verboom2014]. This study provides corroboration, demonstrating that even within a single lineage of moderate size, multiple intrinsic and extrinsic factors have powered diversification. In so doing, this work contributes to a growing body of research which argues that it is no longer sufficient to characterise a radiation simplistically as 'adaptive' or 'non-adaptive' [@Simoes2016; @Lagomarsino2016; Ebersbach2017; @Muellner2019].



 In particular, mountain radiations require a holistic approach to untangle the subtle interaction of geographic and ecological triggers [@Muellner2019].



# References





